### ISSUE TITLE
Answering Analysis/Insight Questions

### ISSUE THREAD

**Issue by SZun** [SZun/Real-Impact-of-Inflation#11]

**Comment by sami-naeem** [comment]
1) The differences between the reported and the actual inflation on a national level. - Sami Naeem
2) The breakdown of the food and energy components of the actual inflation. Energy will be further broken down into gasoline. - Gabriel Millan
3) The differences in inflation between the four different US regions. - Samuel Farrell

**Comment by SZun** [comment]
Question 3 done, questions 1/2 still outstanding @sami-naeem @gjmillan
