### ISSUE TITLE
Creating Analysis/Insight Questions

### ISSUE THREAD

**Issue by SZun** [SZun/Real-Impact-of-Inflation#5]

**Comment by sami-naeem** [comment]
1) The differences between the reported and the actual inflation on a national level. - Sami Naeem
2) The breakdown of the food and energy components of the actual inflation. Energy will be further broken down into gasoline. - Gabriel Millan
3) The differences in inflation between the four different US regions. - Samuel Farrell
4) Time range: 09/2012 - 09/2022
